### ISSUE TITLE
Reading in data.

### ISSUE THREAD

**Issue by eracah** [NERSC/dayabay-learn#4]
The way of reading in data is a bit clunky with the multiple hdf5 files and the preallocating with zeros. Would be nice to have one hdf5 file that we can index from.

That would allow an option for just reading certain amount of data if you just want to do small scale tests.

**Comment by eracah** [comment]
Also moving the data to scratch would be something I am in favor of

**Comment by samkohn** [comment]
I would put them in Cori's scratch but Cori is down till 6/27. Should I move them to dasrepo?

**Comment by samkohn** [comment]
Also I can just generate one large hdf5 file with all of the IBD events.

**Comment by eracah** [comment]
hey. I already did it. it's /project/projectdirs/dasrepo/ibd_pairs/all_pairs.h5
